### ISSUE TITLE
Router/navigation support

### ISSUE THREAD

**Issue by mlynch** [mlynch/nextjs-tailwind-ionic-capacitor-starter#3]
If using Next.js and building both an iOS/Android app and a web app/PWA, you'll need both support for Next.js routing and also quality client-side routing.

This way you can serve up any valid page by navigating directly to it on the web (say, `/about`), complete with static rendering and possibly even SSR, but also navigate to an `about` page client-side complete with transitions and quality native experience users expect.

I wanted to document what I think the best approach here is which is @creativiii's hybrid next/local approach (see his post on this: https://ironeko.com/posts/animating-page-transitions-in-nextjs-for-capacitor?ref=last_articles)

## App Shell

The core idea is that every page serves up an `<AppShell>` component that is essentially all of the `Nav`, `Menu`, `Tabs`, and `PageStack` needed to build the actual client app experience:

<img width="322" alt="Screen Shot 2020-12-30 at 10 46 26 AM" src="https://user-images.githubusercontent.com/11214/103368392-06365400-4a8d-11eb-96d6-b7c4cca5c803.png">

## Client-side routing

Then, instead of using Next.js for actual client-side navigation, we will use a simple client-side router like Wouter: https://github.com/molefrog/wouter

This will handle the "local, client-side" navigation and transitions, but won't handle any "server-side" requests at all.

## Handling Deeplinks

Most apps will want to handle universal links, but the way those URLs are handled is quite different from a product web server and a mobile app which is not running a web server.

Thus, the app will need to handle deeplinks (https://capacitorjs.com/docs/guides/deep-links) and process each request. If it detects that there is an in-app handler for that URL, it will navigate client-side to that page. If not, it will let the browser handle the URL.

## Example page

This is an example of what the Next.js page code would contain:

```javascript
import AppShell from '../components/AppShell';
import Home from '../components/pages/Home';

export default function Index() {
  return <AppShell page={Home} />;
}
```

## `usePage` hook

Then, each page component can use the `usePage` hook to configure app shell related values, such as the title of the page, icons for the tabs, and other values

```javascript
const Home = ({ selected }) => {
  usePage({
    title: 'Home',
  });

  return (
    ...
  )
}
```

## Tasks

- [ ] Abstract away page structure into `AppShell` component
- [ ] Test/integrate client-side router like Wouter
- [ ] Build simple navigation transitions
- [ ] Verify static/SSR support along with client-side routing

**Comment by creativiii** [comment]
Thank you for the mention!

Just wanted to add my two cents on the third party router. While it does work for client side navigation I'm almost 100% sure it will break as soon as deep links are implemented, especially if you're trying to navigate to pages that have not been statically exported.

Say you want to navigate to `pages/post/add`, you will be able to have client side navigation to that page and you could also statically export the page so that deep linking to it is possible.

Unfortunately the same can't be done with pages that aren't statically exported like `pages/post/[some-id]`. You'll be able to navigate to it with wouter from a previous page, but if you try to navigate directly to it from a notification or a link you'll get a 404 as the static html page doesn't actually exist.

Not sure what the best solution is, I just ended up using query strings!

**Comment by mlynch** [comment]
@creativiii good points.

Alright so I'm thinking there's a global deep links handler which will get all URLs (such as universal links) or custom URL schemes that opened the app, and it will be able to process those urls and translate them into the appropriate client-side routes. This mapping could be automated but to start would be manual. Any URLs not handled would then be handled by your browser which would be handled by your production next.js PWA version of this app (or an already existing web app).

When an app is running natively none of the actual generated HTML files from `next export` are loaded except for the `index.html` file, so it's fine if we'd be exporting dynamic pages like `[userId].html`.

Any reactions?

**Comment by creativiii** [comment]
@mlynch So:

> Alright so I'm thinking there's a global deep links handler which will get all URLs (such as universal links) or custom URL schemes that opened the app, and it will be able to process those urls and translate them into the appropriate client-side routes.

This was my first thought as well, but if we're using query string in the URL that need to be interpreted by a handler then why even bother with a middle man at all? The functionality would be very similar to using query strings on their own so we might as well build our navigation around them.

> When an app is running natively none of the actual generated HTML files from next export are loaded except for the index.html file, so it's fine if we'd be exporting dynamic pages like [userId].html.

This is one of the most confusing parts of Next.js so I might be getting this wrong, but I don't think you can have fallback behavior on non-statically exported pages **unless** you're running your app on Vercel. So unless there's a server to route pages that haven't been exported they will end up with a 404.

**Comment by mlynch** [comment]
Good point about query strings, technically we can do whatever we want locally, but would want to support normal URLs for the PWA experience, so if there was just one mapping that would probably be the easiest.

re: export, what I mean is you don't need to have fallback support, because you will never load any of those other HTML files when running natively on mobile. Once the `index.html` file is loaded, all navigation will be client-side. You would need to find a different way to handle those dynamic pages, however.

I'm going to spend some time thinking and playing around with a "universal" approach that uses standard URLs but also can use SSR/static rendering when running as a PWA. If that seems not feasible in Next then I'll try something else.

**Comment by mlynch** [comment]
Made some good progress today: https://github.com/mlynch/nextjs-tailwind-capacitor/tree/routing-refactor

Would love your thoughts on this (still WIP). Specifically, the way `CurrentPage` works now which supports a dual SSR/static render mode for first page content, and then falls back to local routing "at runtime": https://github.com/mlynch/nextjs-tailwind-capacitor/blob/routing-refactor/components/AppShell.jsx#L27

Imagine a deeplink setup handling this stuff and setting the routing info, it would all Just Work.

**Comment by creativiii** [comment]
> Made some good progress today: https://github.com/mlynch/nextjs-tailwind-capacitor/tree/routing-refactor
> 
> Would love your thoughts on this (still WIP). Specifically, the way `CurrentPage` works now which supports a dual SSR/static render mode for first page content, and then falls back to local routing "at runtime": https://github.com/mlynch/nextjs-tailwind-capacitor/blob/routing-refactor/components/AppShell.jsx#L27
> 
> Imagine a deeplink setup handling this stuff and setting the routing info, it would all Just Work.

So, any time a page that can't be statically exported or SSR'd is accessed (like userId) you just load Home instead until the client is ready? That's really neat!

So does Next load `index.html` no matter the route that's being loaded?

**Comment by mlynch** [comment]
No, in that case the `UserDetail` page would still load and be passed the user id and would then load that user client side since you have the client side routes set up for it.

But if you went to that page in the web version of the app `UserDetail` would be SSRed. That make sense?

**Comment by creativiii** [comment]
I didn't even know that was possible with static exporting 🤔

I'm gonna have to give this a spin in an emulator and see how it actually works!

**Comment by mlynch** [comment]
Turns out it's not 😭 at least not officially. However I'm optimistic there's a middle ground. At the very worst it could require two Next.js apps with one just for SSRing but sharing code. https://github.com/vercel/next.js/discussions/15674

At the very least the `getStaticProps` will work fine

**Comment by mlynch** [comment]
Closing as I ended up going with a solution that primarily has Ionic handle routing client side (so you get all the nice transitions and history stack management), and next.js handles any initial load routes and renders the app shell. Works great for iOS and Android apps, not ideal for PWAs but this specific project is initially focused on app store apps.
